"""Add status field to waiting_list table

Revision ID: 0c537949d3b2
Revises: 9f2c1d8a7b44
Create Date: 2026-05-26 12:59:09.905044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c537949d3b2'
down_revision: Union[str, Sequence[str], None] = '9f2c1d8a7b44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waiting_list', sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='applicationstatus'), nullable=False, server_default='PENDING'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waiting_list', 'status')
    # ### end Alembic commands ###
