"""Rename password_hash to hashed_password in User model

Revision ID: ece9b5dabc94
Revises: 61ea49b6f03b
Create Date: 2026-05-18 22:20:13.985551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ece9b5dabc94'
down_revision: Union[str, None] = '61ea49b6f03b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash', new_column_name='hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password', new_column_name='password_hash')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
