"""Add new fields for user and application validation

Revision ID: 61ea49b6f03b
Revises: e0c3b76ddeaf
Create Date: 2026-05-18 21:26:51.350677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61ea49b6f03b'
down_revision: Union[str, None] = 'e0c3b76ddeaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('has_darde', sa.Boolean(), nullable=True))
    op.add_column('applications', sa.Column('previous_education', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('dni_nie', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_users_dni_nie'), 'users', ['dni_nie'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_dni_nie'), table_name='users')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'dni_nie')
    op.drop_column('applications', 'previous_education')
    op.drop_column('applications', 'has_darde')
    # ### end Alembic commands ###
